### ISSUE TITLE
do not mark all functions as having worstDefault side effect

### ISSUE THREAD

**Issue by bloerwald** [wowdev/noggit3#78]

**Comment by ihm-tswow** [comment]
I'm thinking this is something to look carefully at in the long term, and if so, prioritize commonly used inner functions (`vert_*`, `tex_*`, `rand_*` etc.). Some basic tests showed me the performance gain was negligable even for vert functions, but we should analyze it better before deciding on anything.

Keeping `worstDefault` for a function has the benefit that you know for certain that it will work the way it's expressed, and encourages contributors/forks to just go with the safe route instead of guessing (wrong) what their function does to the state. Even I was slightly confused with the way daScript expresses them (is a pure getter `none` or `accessExternal`?): https://dascript.org/doc/reference/embedding/modules.html?highlight=worstdefault#modules-function-sideeffects

**Comment by bloerwald** [comment]
From what I understand
```
int none (int x) { return x + 1; }
void unsafe (bool x) { if (x) std::abort(); }
int modifyExternal (Context* ctx) { return ++ctx→our_data->x; } // implies accessExternal, I guess
int accessExternal (Context* ctx) { return ctx->our_data->x; }
void modifyArgument (int& x) { x += 1; }
int accessGlobal (Context* ctx) { return ctx->their_or_script_data->x; }
void invoke (Context* ctx) { return ctx->their_or_script_data->f(); }
void userScenario() { lol anything, we don't want to model everything, essentially worstDefault, but at least modifyExternal }
```
